### ISSUE TITLE
[ISSUE] cant run with repl.it

### ISSUE THREAD

**Issue by thebedrohlich** [FuckingToasters/discord-group-spammer#10]
im unable to run this on repl.it and i get this error:

![image](https://user-images.githubusercontent.com/93493358/144729845-5a1f70c1-0c72-4ca2-b46d-ca842ba6db0a.png)

**Comment by FuckingToasters** [comment]
The reason for this issue is, that repl.it is a linuxserver and usually the apt command works however repl.it disabled the functionallity. you can remove the function and what is inside def install_modules(): and this should solve it.

**Comment by FuckingToasters** [comment]
I've tried it by myself and can confirm the the issue still existed. i now fixed it with the latest version so you can try to use the latest one. I also work on a bypass for the disocrd security measures, they took after they saw my script :)
