### ISSUE TITLE
Idea for bypass

### ISSUE THREAD

**Issue by TheOnlyWayUp** [FuckingToasters/discord-group-spammer#11]
**Is your feature request related to a problem? Please describe.**
Possible solution to bypass ratelimits

**Describe the solution you'd like**
Let the bot run with multiple accounts and such to create groups, until there are a ton, and add the user to the pre existing groups, not sure if the ratelimit is for creating groups or adding people to them, this'll work if it's just for creating groups, i'll look into the ratelimits in a minute.

**Describe alternatives you've considered**
Support for multiple tokens at once.

**Comment by TheOnlyWayUp** [comment]
I'm unable to find resources/docs about user endpoint ratelimits, could you link some?

**Comment by FuckingToasters** [comment]
Hi, discord bind ratelimits to the account and not the IP so the first thing that comes in mind is to add multiaccount support; The Targets you have need to be friend with you and i guess they will not accept about 300 requests from random users so this would be a issue. creating groups have a 5 minutes ratelimit so you would need to run it on a vServer for some time, adding users to the preexisting groups was the exact thing, that worked before discord noticed, they dont implemented a ratelimit on the group endpoint but theyimplemented a ratelimit about a week ago. I also do not know any docs or resouces about user endpoints and the ratelimits. i guess discord dont make these endpoints public but the way i found the endpoint was really easy, just make a action that you want to do in mass (creating groups, adding to group or other stuff) while havoing the devconsole open. You then will see wich api endpoints it requested what you then can use inside your program. for ratelimits you just can print them into the console.

**Comment by TheOnlyWayUp** [comment]
Yeah, I used to use dev console to map out API Endpoints but I assumed you were using some kind of documentation to get this info. 
Since everything is token based, and adding users to preexisting endpoints is ratelimited, and creating groups is ratelimited, I doubt there's much that can be done apart from adding support for multiple accounts unfortunately. I'll look into making a pr for that if it doesn't exist already.

**Comment by FuckingToasters** [comment]
> 

I had a little script that only requested toe api endpoint and printed the response from a friend, i then added own lot of stuff to the pre existing code that was about 10 lines long. everything is token based, that is true but i did not needed any documentation for it. On any interaction with discord a unique request is being made that you can see in the network tab at the devonconsole, the console not only shows the request links but also shows headers, request payload, jsondata etc. and the structure of such a successful request can be implemented in a pythonscript really easy.
