### ISSUE TITLE
[SUGGESTION] Automatic Phoneverification with a list of Tokens

### ISSUE THREAD

**Issue by bryonpokemon** [FuckingToasters/discord-group-spammer#13]
A auto verifier with 5 sims api for a list of tokens with proxy support

**Comment by FuckingToasters** [comment]
This seem intressting to me. I will try to implement this. It should not be hard to get numbers and the code from the api but i guess the most difficult thing is, to send both with the correct value to the correct discord api. lets see if i manage to do this. I start work on it in a few days.

**Comment by bryonpokemon** [comment]
Yea and discord added a captcha to verify so might have to use captchatools as well

**Comment by FuckingToasters** [comment]
> Yea and discord added a captcha to verify so might have to use captchatools as well

The captcha is only needed sometimes. If Discord want the Program to deliver the solved captcha too it is not hard to do this i guess.

**Comment by FuckingToasters** [comment]
@craycrayum 
> It shows cannot find command git
The Image you tried to upload is not visable. please create a new issue for the problem you are facing instead of asking it in another issue, which is not even related to your issue; thanks.

**Comment by FuckingToasters** [comment]
@bryonpokemon Take a look: https://github.com/FuckingToasters/discord-phone-verifier
