### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Soap41** [FuckingToasters/discord-group-spammer#17]
when i open the .py file its not working, it immediately closes, help

**Comment by FuckingToasters** [comment]
Hi, this happens if there was a error hike running the file. You can try to manually open CMD or PowerShell, then drag & drop the file into CMD or PowerShell and hit enter. This then should give you the error without closing. You can send me the error and I'll be able to help you out.

**Comment by Soap41** [comment]
File "C:\Users\LAPTOP\Documents\discord-group-spammer-main\all_together.py", line 61
    f'[Mass Group Manager] | Ready for use <3')  # windows system
                                             ^
SyntaxError: invalid syntax

**Comment by FuckingToasters** [comment]
> File "C:\Users\LAPTOP\Documents\discord-group-spammer-main\all_together.py", line 61 f'[Mass Group Manager] | Ready for use <3') # windows system ^ SyntaxError: invalid syntax

This don't seem like the full traceback. please send me the full error, otherwise i don't you what the error is.

**Comment by Soap41** [comment]
this is what it says
![image](https://user-images.githubusercontent.com/107049908/176486673-ce0049f0-8c1d-48a2-b87c-74d897d21180.png)

**Comment by FuckingToasters** [comment]
> this is what it says ![image](https://user-images.githubusercontent.com/107049908/176486673-ce0049f0-8c1d-48a2-b87c-74d897d21180.png)

This line is not crucial and can be removed as a quick solution. it only sets the cmd window title which isn't really needed however i will take a look into it soon.
