### ISSUE TITLE
[SUGGESTION] Check if required modules are already installed

### ISSUE THREAD

**Issue by ZenoMilk12** [FuckingToasters/discord-group-spammer#18]
**Is your feature request related to a problem? Please describe.**
Yes. It'll be faster if you checked if the required modules are already there.

**Describe the solution you'd like**
At the end of `install_modules()` above the `os.sytem` thing  add:
 `with open('done.yay', 'w') as f:
        f.close()`
And when the `install_modules()` is called add a check if the path exists:
`if exists('done.yay') == False:
    install_modules()`

**Comment by FuckingToasters** [comment]
> **Is your feature request related to a problem? Please describe.** Yes. It'll be faster if you checked if the required modules are already there.
> 
> **Describe the solution you'd like** At the end of `install_modules()` above the `os.sytem` thing add: `with open('done.yay', 'w') as f: f.close()` And when the `install_modules()` is called add a check if the path exists: `if exists('done.yay') == False: install_modules()`

Sounds good. could you make a pull request?

**Comment by ZenoMilk12** [comment]
> > **Is your feature request related to a problem? Please describe.** Yes. It'll be faster if you checked if the required modules are already there.
> > 
> > **Describe the solution you'd like** At the end of `install_modules()` above the `os.sytem` thing add: `with open('done.yay', 'w') as f: f.close()` And when the `install_modules()` is called add a check if the path exists: `if exists('done.yay') == False: install_modules()`
> 
> Sounds good. could you make a pull request?

Yes, curently i'm on vacation, but when i come back i sure will.☺
P.S : I have acces to my phone tho, not sure if i can make a PR on it.

**Comment by FuckingToasters** [comment]
I don't know why i made the function anyways. i updated the file and now it's automatically installing the libarys in the requirements.txt file.
