### ISSUE TITLE
[BUG] help please aaahhh

### ISSUE THREAD

**Issue by fizzynob** [FuckingToasters/discord-group-spammer#19]
Module not found error?
![image](https://user-images.githubusercontent.com/104747126/178137073-4f503475-5dd7-44df-a9f0-8233145ccceb.png)

**Comment by FuckingToasters** [comment]
> 

You havn't installed requests. run the command `pip install -r requirements.txt` this will install all needed libaries

**Comment by fizzynob** [comment]
it says this now
![image](https://user-images.githubusercontent.com/104747126/178137508-29d60564-f29b-42cb-89f6-94597e110e1b.png)

**Comment by FuckingToasters** [comment]
> it says this now ![image](https://user-images.githubusercontent.com/104747126/178137508-29d60564-f29b-42cb-89f6-94597e110e1b.png)

You not need to start python and run it inside the python cmd. just open normal cmd in the folder of the project (rightclick -> open cmd here) and then type the command without executing python before.
