### ISSUE TITLE
[BUG] KeyError: 'retry_after'

### ISSUE THREAD

**Issue by r0d1337** [FuckingToasters/discord-group-spammer#2]
line 36, in <module>
    except: print(json_resp['retry_after']), time.sleep(json_resp['retry_after'])
KeyError: 'retry_after'

**Comment by FuckingToasters** [comment]
> line 36, in except: print(json_resp['retry_after']), time.sleep(json_resp['retry_after']) KeyError: 'retry_after'

That is weird. I have a version where i edited a bit what might solve it. i will push this version when i am at home. the issue tells you, that in the jsonresponse that you got is no "retry_after" what usually shoud be there. Could you tell me, in wich file this does happen?

**Comment by 9qz** [comment]
this really shouldn't happen unless you changed code.
Try reinstalling

**Comment by FuckingToasters** [comment]
> line 36, in except: print(json_resp['retry_after']), time.sleep(json_resp['retry_after']) KeyError: 'retry_after'

I deleted some files, implemented most stuff in one single file. please try it again using the latest version and let me know if it works. after a inactivity of 1 week i will close this issue.
