### ISSUE TITLE
[BUG] No such File or Directory

### ISSUE THREAD

**Issue by ghost** [FuckingToasters/discord-group-spammer#20]
error

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/85314798/179370940-8a8428b9-b65d-4b01-9903-0a9f08dbac2a.png)

**Comment by ghost** [comment]
i've added a image in the same path named cool and its a jpg not sure why that comes up then the bottom idek

**Comment by FuckingToasters** [comment]
> i've added a image in the same path named cool and its a jpg not sure why that comes up then the bottom idek

The Error at the bottm means, that the api not returned the keyerror which is a result of the first error. so if we solve the first issue the second will be solved too. 

Take a look at the config.json file. You'll need to specify the path of your image. If the Image is in the same folder from which you run all_together.py you only need to specify the imagename in the config.json file (exampleimage.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/85314798/179371562-846fc07c-ce27-429a-b47b-6a5b6878aa69.png)

**Comment by ghost** [comment]
never did any print's on cmd but it made 10 gc's

**Comment by ghost** [comment]
fixed it im just stupid lol

**Comment by FuckingToasters** [comment]
great to hear that you fixed it!

**Comment by ghost** [comment]
yeah thanks for this tool ill see in a few days if its good also hows the proxy support work?

**Comment by FuckingToasters** [comment]
> yeah thanks for this tool ill see in a few days if its good also hows the proxy support work?

Hi again, for the question about the proxy support, it will load the proxies from the file, then it saves IP, Port (useername & password if provided) in a own variable. Then we use the variables to format it to the correct string which is needed to make requests using proxies.If you don't set any prodigy in the file or dint select http / https in the input, the requests will be made without proxies
