### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by regeleDavid900** [FuckingToasters/discord-group-spammer#22]
i tried using it but i cant create goups and i cabnd d onoting my account is verify on phone and email  so its someting i do wrong?

**Comment by FuckingToasters** [comment]
I don't understand your Issue. Open a New Issue with all Details.

**Comment by regeleDavid900** [comment]
If you can make an tutorial download and installing it will be helpfully.
My issue is when I put my token în config ( my token is verify email and
phone and when I click 1.create groups it stay 1 sec and after it close.
Other option didint work too so pleaze I really need an group creAtor
spammer. Thanks

dum., 24 mar. 2024, 20:52 FuckingToasters ***@***.***> a
scris:
