### ISSUE TITLE
config.json not found

### ISSUE THREAD

**Issue by dispaqi** [FuckingToasters/discord-group-spammer#4]
C:\Users\vikwa>C:\Users\vikwa\Downloads\discord-group-spammer-main\discord-group-spammer-main\group_maker.py
Traceback (most recent call last):
  File "C:\Users\vikwa\Downloads\discord-group-spammer-main\discord-group-spammer-main\group_maker.py", line 6, in <module>
    with open("config.json") as conf:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

**Comment by FuckingToasters** [comment]
> C:\Users\vikwa>C:\Users\vikwa\Downloads\discord-group-spammer-main\discord-group-spammer-main\group_maker.py Traceback (most recent call last): File "C:\Users\vikwa\Downloads\discord-group-spammer-main\discord-group-spammer-main\group_maker.py", line 6, in with open("config.json") as conf: FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

try to redownload the files. The config.json file is present in the home dictonary.

**Comment by FuckingToasters** [comment]
Hey, hope you noticed my changes. its a beta version but i work on it to make everything in 1 file with the functunallity to select whatever you want tu use by just running 1 file. Not all functionallys and suggestions i got are added yet but this will be added soon too. Good Luck with my Projects. And remember: Educational only :)

**Comment by dispaqi** [comment]
i will try that when im home, pretty sure i already tried that soon
also cant wait for that (1file)
thanks for educating me

**Comment by dispaqi** [comment]
all together works like p, u should make a discord

**Comment by dispaqi** [comment]
![zz3](https://user-images.githubusercontent.com/37266311/142738652-9b41586e-1771-4a19-bcbc-ec573c2c994c.PNG)

**Comment by dispaqi** [comment]
![image](https://user-images.githubusercontent.com/37266311/142738877-31c751e1-b8dc-4a6e-a5a0-9fc45ef78d35.png)

moved the config.json into my home directory and this happened

**Comment by FuckingToasters** [comment]
> ![image](https://user-images.githubusercontent.com/37266311/142738877-31c751e1-b8dc-4a6e-a5a0-9fc45ef78d35.png)
> 
> moved the config.json into my home directory and this happened

This means that your config is somehow wrong formatted. you could lookup a json validator website to see if there is any issue howerver i just added a updated file `all_together.py` you can redownload the while project, replace the existing pythonfile or just copy the code from `all_together.py` and then let me know, if it works :)

**Comment by dispaqi** [comment]
i used https://jsonformatter.curiousconcept.com/# and it works, thanks so much :D u should make a discord server or something, fixed now

**Comment by FuckingToasters** [comment]
> i used https://jsonformatter.curiousconcept.com/# and it works, thanks so much :D u should make a discord server or something, fixed now

Great to hear that everything is working so far. I actually have linked a Discord Guild Invite on my profile readme. You can join latest guilds even if they become disabled on this link i will update if a invite is invalid: http://discord.verify.gay

**Comment by dispaqi** [comment]
thanks so much :D
