### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by dispaqi** [FuckingToasters/discord-group-spammer#7]
1. (Id like to see this implemented first) Just something simple that shows the total amount of groups you are in

**Comment by FuckingToasters** [comment]
Hey, thank u for the suggestion, 
Showing the amount of groups you are in should not bee that hard. I just need to find the correct api endpoint.
I will work on this when every other implementation, i plan to do is done so far.

**Comment by FuckingToasters** [comment]
make sure to create a good issue. when creating a issue you find a template for issues and suggestions. filling the template give me a better point to start and a work on the issue / suggested feature can be done faster.
