### ISSUE TITLE
Add proxies

### ISSUE THREAD

**Issue by astra1234** [FuckingToasters/discord-group-spammer#8]
Proxies

**Comment by FuckingToasters** [comment]
Hey, on the readme you will see that different features will be added in a few months. i also mention that this version might be a paid one but not sure tho.
I have to do some school stuff to complete and i will update the code with improvements and new features that are not really big.

**Comment by FuckingToasters** [comment]
make sure to create a good issue. when creating a issue you find a template for issues and suggestions. filling the template give me a better point to start and a work on the issue / suggested feature can be done faster.
