### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ZychereqRel** [FuckingToasters/discord-group-spammer#9]
[Final] Select a Option from above: 1
Traceback (most recent call last):
  File "C:\Users\I7\Desktop\discord-group-spammer-main\all_together.py", line 121, in <module>
    bot.setDmGroupIcon(group_id, image_path)
  File "C:\Users\I7\AppData\Local\Programs\Python\Python39\lib\site-packages\discum\discum.py", line 207, in setDmGroupIcon
    return imports.Messages(self.discord,self.s,self.log).setDmGroupIcon(channelID, imagePath)
  File "C:\Users\I7\AppData\Local\Programs\Python\Python39\lib\site-packages\discum\messages\messages.py", line 78, in setDmGroupIcon
    with open(imagePath, "rb") as image:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/image/cool.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\I7\Desktop\discord-group-spammer-main\all_together.py", line 137, in <module>
    f"{colorama.Fore.LIGHTRED_EX}    [429] Discord reject requests for {json_resp['retry_after']} Seconds now. I will continue after that time...{colorama.Fore.RESET}")
KeyError: 'retry_after'
any idea?

**Comment by FuckingToasters** [comment]
> [Final] Select a Option from above: 1 Traceback (most recent call last): File "C:\Users\I7\Desktop\discord-group-spammer-main\all_together.py", line 121, in bot.setDmGroupIcon(group_id, image_path) File "C:\Users\I7\AppData\Local\Programs\Python\Python39\lib\site-packages\discum\discum.py", line 207, in setDmGroupIcon return imports.Messages(self.discord,self.s,self.log).setDmGroupIcon(channelID, imagePath) File "C:\Users\I7\AppData\Local\Programs\Python\Python39\lib\site-packages\discum\messages\messages.py", line 78, in setDmGroupIcon with open(imagePath, "rb") as image: FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/image/cool.jpg'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\Users\I7\Desktop\discord-group-spammer-main\all_together.py", line 137, in f"{colorama.Fore.LIGHTRED_EX} [429] Discord reject requests for {json_resp['retry_after']} Seconds now. I will continue after that time...{colorama.Fore.RESET}") KeyError: 'retry_after' any idea?

Next time please choose the Template and build your own issues in the way the templte is built. I can not really help much witch just a error code. on a good question a good answer will follow.
The issue clearly says. that you do not have a image cool.jpg in path. make sure to find an image, download it and rename it to cool.jpg or change the name in config.json. f the image is in the same path where the all_together.py file is, you only need to set the name in the config without need to type the path.
